### ISSUE TITLE
Performing successful query against Vault SQL Database

### ISSUE THREAD

**Issue by JordiFabregatJunior** [JordiFabregatJunior/TestJFD#14]
## ToDo
+ [ ] GetStarted with LinqPad
+ [ ] [Add connection to Vault SQL database](https://blog.coolorange.com/2014/05/23/how-to-effectively-manipulate-bcp-packages/)
+ [ ] Perform basic select statement for a file
