### ISSUE TITLE
Feeding IDBVI (Intermediate database)

### ISSUE THREAD

**Issue by JordiFabregatJunior** [JordiFabregatJunior/TestJFD#15]
## Details

In the [LOAD process](https://coolorange.atlassian.net/wiki/spaces/LOAD/pages/935854091/Project+Guidelines+Load+-+Legacy+to+Vault#Load-Phases) for legacy migrations to Vault, the reseller should fill an SQL intermediate database template that coolOrange could easily read to create a proper bcpPackage.

## ToDo

+ [ ] Get [Intermediate database template](https://coolorange.atlassian.net/wiki/spaces/LOAD/pages/855474185/Description+of+the+coolOrange+Intermediate+Database+for+Vault+Import) (Markus or Christian)
+ [ ] From #14 , extend queries to extract corresponding data from test Vault
+ [ ] Import data to IDB
